apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: todo-web
          image: moessam634/todo-list-nodejs-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: mongoDbUrl
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: mongoDbUrl
