apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo
type: Opaque
stringData:
  mongoDbUrl: "mongodb+srv://todo-user:3dDvMWS5Q4SKLqOs@todo-cluster.htroypt.mongodb.net/?appName=todo-cluster"
