apiVersion: v1
kind: Service
metadata:
  name: todo-web
  namespace: todo
spec:
  selector:
    app: todo-web
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 4000
      nodePort: 30080
